<?php
return array (
  'title' => '中国',
  'style' => '1',
  'siteid' => '1',
  'data' => 
  array (
    3361 => 
    array (
      'linkageid' => '3361',
      'name' => '北京市',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3362 => 
    array (
      'linkageid' => '3362',
      'name' => '上海市',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3363 => 
    array (
      'linkageid' => '3363',
      'name' => '天津市',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3364 => 
    array (
      'linkageid' => '3364',
      'name' => '重庆市',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3365 => 
    array (
      'linkageid' => '3365',
      'name' => '河北省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3366 => 
    array (
      'linkageid' => '3366',
      'name' => '山西省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3367 => 
    array (
      'linkageid' => '3367',
      'name' => '内蒙古',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3368 => 
    array (
      'linkageid' => '3368',
      'name' => '辽宁省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3369 => 
    array (
      'linkageid' => '3369',
      'name' => '吉林省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3370 => 
    array (
      'linkageid' => '3370',
      'name' => '黑龙江',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3371 => 
    array (
      'linkageid' => '3371',
      'name' => '江苏省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3372 => 
    array (
      'linkageid' => '3372',
      'name' => '浙江省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3373 => 
    array (
      'linkageid' => '3373',
      'name' => '安徽省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3374 => 
    array (
      'linkageid' => '3374',
      'name' => '福建省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3375 => 
    array (
      'linkageid' => '3375',
      'name' => '江西省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3376 => 
    array (
      'linkageid' => '3376',
      'name' => '山东省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3377 => 
    array (
      'linkageid' => '3377',
      'name' => '河南省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3378 => 
    array (
      'linkageid' => '3378',
      'name' => '湖北省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3379 => 
    array (
      'linkageid' => '3379',
      'name' => '湖南省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3380 => 
    array (
      'linkageid' => '3380',
      'name' => '广东省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3381 => 
    array (
      'linkageid' => '3381',
      'name' => '广西省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3382 => 
    array (
      'linkageid' => '3382',
      'name' => '海南省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3383 => 
    array (
      'linkageid' => '3383',
      'name' => '四川省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3384 => 
    array (
      'linkageid' => '3384',
      'name' => '贵州省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3385 => 
    array (
      'linkageid' => '3385',
      'name' => '云南省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3386 => 
    array (
      'linkageid' => '3386',
      'name' => '西藏',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3387 => 
    array (
      'linkageid' => '3387',
      'name' => '陕西省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3388 => 
    array (
      'linkageid' => '3388',
      'name' => '甘肃省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3389 => 
    array (
      'linkageid' => '3389',
      'name' => '青海省',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3390 => 
    array (
      'linkageid' => '3390',
      'name' => '宁夏',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
    3391 => 
    array (
      'linkageid' => '3391',
      'name' => '新疆',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'siteid' => '0',
    ),
  ),
);
?>