<?php
return array (
  3 => 
  array (
    'id' => '3',
    'catid' => '9',
    'typeid' => '0',
    'title' => '电池厂家',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://localhost/diandongche/index.php?m=content&c=index&a=show&catid=9&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1312204129',
    'updatetime' => '1313585824',
    'hitsid' => 'c-12-3',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '9',
    'typeid' => '0',
    'title' => '绿源厂家',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://localhost/diandongche/index.php?m=content&c=index&a=show&catid=9&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1314108101',
    'updatetime' => '1314380350',
    'hitsid' => 'c-12-4',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '9',
    'typeid' => '0',
    'title' => '小鸟厂家',
    'style' => '',
    'thumb' => '',
    'keywords' => '小鸟 厂家',
    'description' => '小鸟厂家小鸟厂家小鸟厂家小鸟厂家小鸟厂家小鸟厂家小鸟厂家小鸟厂家小鸟厂家小鸟厂家小鸟厂家小鸟厂家小鸟厂家小鸟厂家小鸟厂家小鸟厂家',
    'posids' => '0',
    'url' => 'http://localhost/diandongche/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1307351371',
    'updatetime' => '1307351434',
    'hitsid' => 'c-12-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>